### PR TITLE
Update Readme for this project

### LINKED ISSUE #6: Consider edit clearity readme for this project or remove it.

### PR DESCRIPTION
**Pull request by hamidroohi71**
Close #6

### CODE REVIEW

**Comment by nblogist** [comment]
Please have a readme . Put a proper title "DC DAO Website" along with a short description as in the website to help people willing to do stuff in Web3 then also add all the social links 
Plus instructions on how to run the project.

**Review by nblogist — CHANGES_REQUESTED** [review]
Removing readme is not a good practice

**Comment by hamidroohi71** [comment]
Ok. I will do it now

**Comment by hamidroohi71** [comment]
Readme added with proper content

**Pull request merged**
